/*
 * SPDX-FileCopyrightText: 2015 - 2025 Rime community
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
import com.android.build.api.dsl.ApplicationExtension
import com.android.build.gradle.tasks.ExternalNativeBuildTask
import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.Delete
import org.gradle.kotlin.dsl.register
import java.io.File
import java.util.Properties

open class NativeBaseConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        target.pluginManager.apply("com.android.application")
        target.extensions.configure(ApplicationExtension::class.java) {
            ndkVersion = target.ndkVersion
            defaultConfig {
                @Suppress("UnstableApiUsage")
                externalNativeBuild {
                    cmake {
                        val args = mutableListOf("-DANDROID_STL=c++_static")
                        if (target.qnnSdkRoot != null) {
                            args.add("-DQNN_SDK_ROOT=${target.qnnSdkRoot}")
                        }
                        arguments(*args.toTypedArray())
                    }
                }
            }

            if (target.file("prebuilt").exists()) {
                sourceSets.getByName("main").jniLibs.directories.add("prebuilt")
            } else {
                externalNativeBuild {
                    cmake {
                        version = target.cmakeVersion
                        path("src/main/jni/CMakeLists.txt")
                    }
                }
            }

            // Pre-packaged voice runtime libs (onnxruntime + QNN DSP) are staged here
            sourceSets.getByName("main").jniLibs.directories.add(
                target.layout.buildDirectory.dir("generated/voiceJniLibs").get().asFile.absolutePath,
            )

            splits.abi {
                isEnable = true
                isUniversalApk = false
                reset()
                (target.buildAbiOverride?.split(",") ?: Versions.supportedAbis).forEach {
                    include(it)
                }
            }
        }
        registerCleanCxxTask(target)
        registerPatchApplyTask(target)
        registerNativeCacheTasks(target)
        registerVoiceRuntimePackagingTask(target)
    }

    private fun registerNativeCacheTasks(project: Project) {
        val jniDir = project.file("src/main/jni")

        fun abi(): String = project.buildAbiOverride
            ?.split(",")?.firstOrNull()
            ?: Versions.supportedAbis.first()

        fun buildTypeFromNativeBuild(taskName: String): String {
            val base = taskName
                .removePrefix("externalNativeBuild")
                .removePrefix("buildCMake")
            val raw = base.substringBefore("[").lowercase()
            return when (raw) {
                "relwithdebinfo", "minsizerel" -> "release"
                else -> raw
            }
        }

        val prepareTasks = listOf("debug", "release").associate { bt ->
            val cacheDir = NativeCacheManager.cacheDir(project, bt)
            val cacheStateFile = File(cacheDir, "NativeCacheState.cmake")

            bt to project.tasks.register("prepareNativeCache${bt.replaceFirstChar { it.uppercaseChar() }}") {
                group = "native"
                description = "Compute native source hashes for $bt and skip cached components"
                inputs.dir(jniDir)
                outputs.upToDateWhen { false }

                doFirst {
                    val hashes = NativeCacheManager.computeHashes(jniDir)
                    val cachePropFile = File(project.layout.buildDirectory.get().asFile, "nativeCacheState-$bt.properties")
                    val props = Properties()

                    project.logger.lifecycle("--- Native cache status [$bt] ---")
                    for (comp in NativeCacheManager.Component.entries) {
                        val cached = NativeCacheManager.readCachedHash(cacheDir, comp)
                        val skip = hashes[comp] == cached && cached != null
                        props.setProperty("skip_${comp.cacheKey}", skip.toString())
                        val status = if (skip) "CACHED" else "NEED BUILD"
                        project.logger.lifecycle("  ${comp.name}: $status")
                    }

                    cachePropFile.parentFile.mkdirs()
                    cachePropFile.outputStream().use { props.store(it, null) }

                    val sb = StringBuilder()
                    sb.appendLine("# Generated by prepareNativeCache — do not edit")
                    for (comp in NativeCacheManager.Component.entries) {
                        val cached = NativeCacheManager.readCachedHash(cacheDir, comp)
                        val skip = hashes[comp] == cached && cached != null
                        val cmakeVar = when (comp) {
                            NativeCacheManager.Component.RIME -> "SKIP_RIME_TARGETS"
                            NativeCacheManager.Component.LUA_THEME -> "SKIP_LUA_THEME_TARGETS"
                            NativeCacheManager.Component.SHERPA -> "SKIP_SHERPA_TARGETS"
                        }
                        sb.appendLine("set($cmakeVar ${if (skip) "ON" else "OFF"} CACHE BOOL \"\" FORCE)")
                    }

                    cacheStateFile.parentFile.mkdirs()
                    cacheStateFile.writeText(sb.toString())
                }
            }
        }

        project.tasks.withType(ExternalNativeBuildTask::class.java).configureEach {
            val bt = buildTypeFromNativeBuild(name)
            val cmakeBuildType = name
                .removePrefix("externalNativeBuild")
                .removePrefix("buildCMake")
                .substringBefore("[")
            val cacheDir = NativeCacheManager.cacheDir(project, bt)
            val stateFile = File(cacheDir, "NativeCacheState.cmake")
            val cachePropFile = File(project.layout.buildDirectory.get().asFile, "nativeCacheState-$bt.properties")

            inputs.file(stateFile)
            prepareTasks[bt]?.let { dependsOn(it) }

            doLast {
                if (!cachePropFile.exists()) return@doLast
                val props = Properties()
                cachePropFile.inputStream().use { props.load(it) }

                val cxxBase = project.file("build/intermediates/cxx")
                val objDirs = project.fileTree(cxxBase).matching { include("**/obj") }
                val objRoot = objDirs.firstOrNull()
                    ?: run {
                        val cxxBuild = project.file(".cxx")
                        val btDir = File(cxxBuild, cmakeBuildType)
                        val hashDir = btDir.listFiles()
                            ?.filter { it.isDirectory }
                            ?.maxByOrNull { it.lastModified() }
                        if (hashDir != null) {
                            File(cxxBase, "$cmakeBuildType/${hashDir.name}/obj").also { it.mkdirs() }
                        } else {
                            null
                        }
                    }
                if (objRoot != null) {
                    for (comp in NativeCacheManager.Component.entries) {
                        val skip = props.getProperty("skip_${comp.cacheKey}")?.toBoolean() ?: false
                        if (skip) {
                            NativeCacheManager.restoreFromCache(cacheDir, comp, abi(), objRoot)
                        }
                    }
                }

                for (comp in NativeCacheManager.Component.entries) {
                    val skip = props.getProperty("skip_${comp.cacheKey}")?.toBoolean() ?: false
                    if (!skip) {
                        NativeCacheManager.cacheFromObjDir(project, comp, abi(), cacheDir)

                        val hashes = NativeCacheManager.computeHashes(jniDir)
                        val hash = hashes[comp]
                        if (hash != null) {
                            NativeCacheManager.writeCachedHash(cacheDir, comp, hash)
                            project.logger.lifecycle("Cached to disk [$bt]: ${comp.name}")
                        }
                    }
                }
            }
        }

        for (bt in listOf("debug", "release")) {
            project.tasks.configureEach {
                if (name == "pre${bt.replaceFirstChar { it.uppercaseChar() }}Build") {
                    prepareTasks[bt]?.let { dependsOn(it) }
                }
            }
        }
    }

    private fun registerVoiceRuntimePackagingTask(project: Project) {
        val outDir = project.file("build/generated/voiceJniLibs")
        val abis = project.buildAbiOverride?.split(",") ?: Versions.supportedAbis.toList()

        val packageTask =
            project.tasks.register("packageVoiceRuntimeLibs") {
                group = "native"
                description = "Pre-package voice runtime libraries (onnxruntime + QNN DSP) into the APK"
                outputs.dir(outDir)

                doLast {
                    if (project.file("prebuilt").exists()) {
                        project.logger.warn(
                            "app/prebuilt exists; voice runtime pre-packaging skipped " +
                                "(prebuilt/ must include the runtime .so libraries)",
                        )
                        return@doLast
                    }

                    // libonnxruntime.so — produced locally by the sherpa-onnx native build
                    for (abi in abis) {
                        val onnx =
                            project.fileTree(project.file(".cxx")).matching {
                                include("**/onnxruntime-android-*/jni/$abi/libonnxruntime.so")
                            }.firstOrNull()
                                ?: error(
                                    "libonnxruntime.so for $abi not found under .cxx. " +
                                        "Run the external native build first.",
                                )
                        val targetDir = File(outDir, abi).apply { mkdirs() }
                        val dest = File(targetDir, "libonnxruntime.so")
                        if (!dest.exists() || dest.length() != onnx.length()) {
                            onnx.copyTo(dest, overwrite = true)
                            project.logger.lifecycle("Pre-packaged libonnxruntime.so ($abi)")
                        }
                    }

                    // QNN DSP (arm64-v8a only, from the local QNN SDK), variant from qnnVariant
                    if (abis.contains("arm64-v8a")) {
                        val qnnRoot = project.qnnSdkRoot?.let { File(it) }
                        val variant = project.qnnVariant
                        if (qnnRoot != null && qnnRoot.isDirectory && variant != null) {
                            val version = variant.removePrefix("v")
                            val libs =
                                listOf(
                                    "libQnnHtp.so",
                                    "libQnnSystem.so",
                                    "libQnnHtpPrepare.so",
                                    "libQnnHtpV${version}Stub.so",
                                ).map { File(qnnRoot, "lib/aarch64-android/$it") } +
                                    File(
                                        qnnRoot,
                                        "lib/hexagon-$variant/unsigned/libQnnHtpV${version}Skel.so",
                                    )
                            val missing = libs.filterNot { it.isFile }
                            if (missing.isNotEmpty()) {
                                throw GradleException(
                                    "QNN SDK incomplete at $qnnRoot for variant $variant; missing: " +
                                        missing.joinToString { it.path },
                                )
                            }
                            val targetDir = File(outDir, "arm64-v8a").apply { mkdirs() }
                            for (src in libs) {
                                val dest = File(targetDir, src.name)
                                if (!dest.exists() || dest.length() != src.length()) {
                                    src.copyTo(dest, overwrite = true)
                                }
                            }
                            project.logger.lifecycle("Pre-packaged QNN DSP $variant libraries")
                        } else {
                            project.logger.warn(
                                "QNN_SDK_ROOT/qnnSdkRoot or QNN_VARIANT/qnnVariant not set; " +
                                    "QNN DSP libs will NOT be pre-packaged (QNN voice will be unavailable)",
                            )
                        }
                    }
                }
            }

        project.tasks.withType(ExternalNativeBuildTask::class.java).configureEach {
            // Order after the native build so the .so files exist, but do not force
            // unrelated variants to build (mustRunAfter only affects tasks in the graph).
            packageTask.get().mustRunAfter(this)
        }

        // Package the staged libs into the APK before native lib merging
        project.tasks.configureEach {
            val isMergeConsumer =
                (name.startsWith("merge") && name.endsWith("NativeLibs")) ||
                    (name.startsWith("merge") && name.endsWith("JniLibFolders"))
            if (isMergeConsumer) {
                dependsOn(packageTask)
            }
        }
    }

    private fun registerPatchApplyTask(project: Project) {
        val rootDir = project.rootDir
        val jniDir = "app/src/main/jni"
        val macrosHeader = project.file("src/main/jni/sherpa-onnx/sherpa-onnx/csrc/macros.h")
        val tableTranslatorH = project.file("src/main/jni/librime/src/rime/gear/table_translator.h")
        val luaCmake = project.file("src/main/jni/librime-plugins/librime-lua/CMakeLists.txt")
        val luaLiolib = project.file("src/main/jni/librime-plugins/librime-lua-deps/lua5.5/liolib.c")
        val witogramCc = project.file("src/main/jni/librime-plugins/librime-witogram/src/witogram.cc")
        val applyPatches =
            project.tasks.register("applyNativePatches") {
                group = "native"
                description = "Apply patches required for native build (sherpa-onnx-qnn + librime-custom + librime-plugins)"
                doLast {
                    ProcessBuilder(
                        "git",
                        "apply",
                        "--directory=$jniDir/sherpa-onnx",
                        "patches/sherpa-onnx-qnn.patch",
                    ).directory(rootDir).inheritIO().start().waitFor()
                    ProcessBuilder(
                        "git",
                        "apply",
                        "--directory=$jniDir/librime",
                        "patches/librime-custom.patch",
                    ).directory(rootDir).inheritIO().start().waitFor()
                    ProcessBuilder(
                        "git",
                        "apply",
                        "--directory=$jniDir/librime-plugins/librime-lua",
                        "patches/librime-lua.patch",
                    ).directory(rootDir).inheritIO().start().waitFor()
                    ProcessBuilder(
                        "git",
                        "apply",
                        "--directory=$jniDir/librime-plugins/librime-lua-deps",
                        "patches/lua.patch",
                    ).directory(rootDir).inheritIO().start().waitFor()
                    ProcessBuilder(
                        "git",
                        "apply",
                        "--directory=$jniDir/librime-plugins/librime-witogram",
                        "patches/librime-witogram.patch",
                    ).directory(rootDir).inheritIO().start().waitFor()
                }
                outputs.upToDateWhen {
                    (macrosHeader.exists() && macrosHeader.readText().contains("throw std::runtime_error")) &&
                        (tableTranslatorH.exists() && tableTranslatorH.readText().contains("min_word_length")) &&
                        (luaLiolib.exists() && luaLiolib.readText().contains("!defined(ANDROID)")) &&
                        (luaCmake.exists() && luaCmake.readText().contains("lua-utf8")) &&
                        (witogramCc.exists() && witogramCc.readText().contains("Fallback to KenLM"))
                }
            }

        project.tasks.withType(ExternalNativeBuildTask::class.java).configureEach {
            dependsOn(applyPatches)
        }
    }

    private fun registerCleanCxxTask(project: Project) {
        project
            .tasks.register<Delete>("cleanCxxIntermediates") {
                delete(project.file(".cxx"))
            }.also {
                project.cleanTask.dependsOn(it)
            }
    }
}
