# SPDX-FileCopyrightText: 2015 - 2024 Rime community
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Install Android NDK
        run: sdkmanager --install "cmake;4.1.2"

      - name: Compute build version name
        run: |
          echo "BUILD_VERSION_NAME=$(git describe --tags --long --always --exclude=nightly)" >> $GITHUB_ENV

      - name: Calculate JNI cache hash
        id: cache-hash
        run: ./gradlew :app:calculateNativeCacheHash

      - name: Fetch JNI cache
        uses: actions/cache@v5
        id: jni-cache
        with:
          path: "app/prebuilt"
          key: ${{ runner.os }}-trime-jni-release-${{ steps.cache-hash.outputs.native-cache-hash }}

      - name: Setup Keystore
        run: |
          cat << EOF > keystore.properties
          keyBase64=${{ secrets.SIGNING_KEY }}
          storePassword=${{ secrets.KEY_STORE_PASSWORD }}
          keyAlias=${{ secrets.ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build LyraIME
        run: make release

      - name: Add JNI cache
        if: ${{ !steps.jni-cache.outputs.cache-hit }}
        run: cp -R app/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib app/prebuilt

      - name: Rename APK
        run: |
          for f in app/build/outputs/apk/release/*.apk; do
            mv "$f" "app/build/outputs/apk/release/LyraIME-${BUILD_VERSION_NAME}.apk"
          done

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lyraime-build
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error

  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    needs: build
    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: lyraime-build
          path: apks

      - name: Create Nightly release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: nightly
          prerelease: true
          title: "Nightly Build"
          files: apks/*.apk
